openapi: 3.0.4
info:
  title: Ai-Recruter
  version: 1.0.12
servers:
  - url: http://localhost:3000
tags:
  - name: users
    description: пользователи
  - name: dashboard
    description: дашбоард
  - name: candidates
    description: кандидаты
  - name: auth
    description: аутентификация
  - name: vacancies
    description: вакансии

paths:
  /users/{userId}:
    get:
      operationId: getUsersList
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/UsersListResponses'
    patch:
      operationId: updateUser
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersPatch'
      responses:
        200:
          $ref: '#/components/responses/CandidatesListResponses'
    delete:
      operationId: deleteUser
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        204:
          $ref: '#/components/responses/UsersListResponses'
  #кандидаты
  /candidates:
    get:
      operationId: getCandidatesList
      tags:
        - candidates
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/CandidatesListResponses'
  /candidates/{candidateId}:
    get:
      operationId: getCandidateById
      tags:
        - candidates
      parameters:
        - name: candidateId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/CandidatesListResponses'
  /auth/login:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLogin'
      responses:
        200:
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }
  /dashboard/stats:
    get:
      tags:
        - dashboard
      security:
        - bearerAuth: []
      responses:
        200:
          $ref: '#/components/responses/DashboardResponses'
  /vacancies:
    get:
      operationId: getVacanciesList
      tags:
        - vacancies
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/VacanciesListResponses'
components:
  schemas:
    UsersPatch:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
    Users:
      type: object
      required:
        - id
        - email
        - password
        - isActive
        - createdAt
      properties:
        id:
          type: number
        email:
          type: string
        password:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
    Candidates:
      type: object
      required:
        - id
        - fullName
        - email
        - phone
        - birthData
        - currentStatus
        - createdAt
      properties:
        id:
          type: number
        fullName:
          type: string
        email:
          type: string
        phone:
          type: number
        birthData:
          type: string
          format: date
        currentStatus:
          type: string
        createdAt:
          type: string
          format: date-time
    DashboardStats:
      type: object
      properties:
        totalCandidates:
          type: integer
        newCandidates:
          type: integer
        primarySelection:
          type: integer
        docVerif:
          type: integer
        readyForRegis:
          type: integer
        latestCandidates:
          type: integer
        hiringFunnel:
          type: integer
    AuthLogin:
      type: object
      required: [email, password]
      properties:
        email: { type: string }
        password: { type: string }
    Vacancies:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        departament:
          type: string
        location:
          type: string
        required_license_category:
          type: string
        status:
          type: string

    AuthLoginToken:
      type: object
      properties:
        token: { type: string }

  responses:
    UsersListResponses:
      description: Список пользователей
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Users'
    UserResponses:
      description: Пользователь
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Users'
    CandidatesListResponses:
      description: Список кандидатов
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Candidates'
    VacanciesListResponses:
      description: Список вакансий
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Vacancies'
    DashboardResponses:
      description: Дашбоард
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/DashboardStats'
    AuthLoginResponses:
      description: Успешный вход
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthLoginToken'
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JW
