openapi: 3.0.4
info:
  title: Ai-Recruter
  version: 1.0.12
servers:
  - url: http://localhost:3000/api
tags:
  - name: users
    description: пользователи
  - name: dashboard
    description: дашбоард
  - name: candidates
    description: кандидаты
  - name: auth
    description: аутентификация

paths:
  /users:
    get:
      operationId: getUsersList
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/UsersListRespones'
    post:
      operationId: createUser
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        201:
          $ref: '#/components/responses/UserRespones'

  /users/{userId}:
    patch:
      operationId: updateUser
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersPatch'
      responses:
        200:
          $ref: '#/components/responses/CandidatesListRespones'
    delete:
      operationId: deleteUser
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        204:
          $ref: '#/components/responses/UsersListRespones'
  #кандидаты
  /candidates:
    get:
      operationId: getCandidatesList
      tags:
        - candidates
      parameters:
        - name: q
          in: query
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/CandidatesListRespones'

  /candidates/{candidateId}:
    patch:
      operationId: updateCandidate
      tags:
        - candidates
      parameters:
        - $ref: '#/components/parameters/CandidateId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersPatch'
      responses:
        200:
          $ref: '#/components/responses/CandidatesListRespones'
    delete:
      operationId: deleteCandidate
      tags:
        - candidates
      parameters:
        - $ref: '#/components/parameters/CandidateId'
      responses:
        204:
          $ref: '#/components/responses/CandidatesListRespones'

components:
  schemas:
    UsersPatch:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
    Users:
      type: object
      required:
        - id
        - email
        - password
        - isActive
        - createdAt
      properties:
        id:
          type: number
        email:
          type: string
        password:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
    Candidates:
      type: object
      required:
        - id
        - fullName
        - email
        - phone
        - birthData
        - currentStatus
        - createdAt
      properties:
        id:
          type: number
        fullName:
          type: string
        email:
          type: string
        phone:
          type: number
        birthData:
          type: string
          format: date
        currentStatus:
          type: string
        createdAt:
          type: string
          format: date-time

  responses:
    UsersListRespones:
      description: Список пользователей
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Users'
    UserRespones:
      description: Пользователь
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Users'
    CandidatesListRespones:
      description: Список кандидатов
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Candidates'
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      schema:
        type: string
    CandidateId:
      in: path
      name: CandidateId
      required: true
      schema:
        type: string
